# Generated by Django 3.2.3 on 2021-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimage', models.ImageField(upload_to='carsimages')),
                ('company', models.CharField(max_length=60)),
                ('modelno', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('power', models.IntegerField()),
                ('autodrive', models.BooleanField(default=False)),
                ('nitro', models.BooleanField(default=False)),
                ('autogear', models.BooleanField(default=False)),
                ('millage', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('launchdata', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(max_length=10)),
                ('isSport', models.BooleanField(default=False)),
            ],
        ),
    ]
