# Generated by Django 3.2.3 on 2021-06-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210601_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carimage',
        ),
        migrations.CreateModel(
            name='Carimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimage', models.ImageField(upload_to='carsimages')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
    ]
