# Generated by Django 3.2.3 on 2021-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210603_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(null=True, to='car.Color'),
        ),
    ]
