# Generated by Django 3.2 on 2021-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('standerd', models.CharField(max_length=2)),
                ('percentage', models.CharField(max_length=5)),
                ('height', models.FloatField(max_length=12)),
            ],
        ),
    ]
